server:
  port: 8081
spring:
  application:
    name: Chat_App


# mysql database configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: root

# Hibernate configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect






springdoc:
  api-docs:
    enabled: true
#    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
#  paths-to-match: /chat/**
#
#
#openapi: # Correct spelling
#    dev-url: http://localhost:8083
#    prod-url: http://localhost:8083
#

chat:
  frontend:
    url: http://localhost:3000




